AllCops:
  TargetRubyVersion: 2.5.1
  TargetRailsVersion: 5.2
  DisplayCopNames: true
  ExtraDetails: true
  Include:
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/models/**/*'
    - 'app/helpers/**/*'
    - 'db/migrate/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/DotPosition:
  EnforcedStyle: trailing
