# Common configuration.
AllCops:
  # Include gemspec and Rakefile
  DisplayCopNames: true
  ExtraDetails: true
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
  Exclude:
    - 'db/schema.rb'
Metrics/MethodLength:
  Max: 10
  Exclude: 
    - 'spec/**/*'
