AllCops:
  TargetRubyVersion: 2.5.3
  TargetRailsVersion: 5.2
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 20

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "test/**/*"

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/policies/**/*'
    - 'app/models/**/*'
    - 'app/helpers/**/*'
    - 'test/**/*'
    - 'db/migrate/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/DotPosition:
  EnforcedStyle: trailing

