FROM ruby
ENV PROJECT_ROOT /usr/src/app
ENV BUNDLE_PATH $PROJECT_ROOT/vendor/bundle
ENV GEM_HOME $PROJECT_ROOT/vendor/bundle
RUN apt-get update && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  && rm -rf /var/lib/apt/lists/*t
WORKDIR $PROJECT_ROOT

