frontend_watch:
	WEBPACKER_DEV_SERVER_HOST=webpacker bundle exec bin/webpack-dev-server --inline true

build-production:
	docker build -t naumenkonikita/diplom_project:$(T) -f services/app/Dockerfile.production services/app



