
default: &default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  adapter: postgresql
  encoding: unicode
  port: <%= ENV['DB_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
