---

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  username: postgres
  password:
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: apptest
  username: postgres
  password:
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
